-- MySQL Script generated by MySQL Workbench
-- 05/03/16 22:58:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`hospital` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `account` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hospital`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`department` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `hospital_id` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `FKn8lq60po1t7p42oslqbk61wnu` (`hospital_id` ASC),
  CONSTRAINT `FKn8lq60po1t7p42oslqbk61wnu`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `hospital`.`hospital` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hospital`.`title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`title` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `fee` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hospital`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`doctor` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `sex` INT(11) NULL DEFAULT NULL,
  `work_age` INT(11) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `pre_time_patient` INT NULL,
  `department_id` VARCHAR(255) NULL,
  `title_id` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `FK75x47tyyeco3xj4cmlhj8v6ta` (`department_id` ASC),
  INDEX `FKi8noj4oyoh00xpkq7bs2ym212` (`title_id` ASC),
  CONSTRAINT `FKi8noj4oyoh00xpkq7bs2ym212`
    FOREIGN KEY (`title_id`)
    REFERENCES `hospital`.`title` (`id`),
  CONSTRAINT `FK75x47tyyeco3xj4cmlhj8v6ta`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospital`.`department` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hospital`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`patient` (
  `id` VARCHAR(255) NOT NULL,
  `account` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `sex` INT(11) NULL DEFAULT NULL,
  `bank_account` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hospital`.`time_quantum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`time_quantum` (
  `id` VARCHAR(255) NOT NULL,
  `hour` INT(11) NULL DEFAULT NULL,
  `minute` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hospital`.`registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`registration` (
  `id` VARCHAR(255) NOT NULL,
  `year` INT NULL,
  `month` INT NULL,
  `has_paid` BIT(1) NULL,
  `doctor_id` VARCHAR(255) NOT NULL,
  `patient_id` VARCHAR(255) NOT NULL,
  `time_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKdn9ekl8482cpt21remcdi8cy9` (`doctor_id` ASC),
  INDEX `FK6dwehthu61quieqm0dhcf45dt` (`patient_id` ASC),
  INDEX `FKk4nxa3jk494rjdtmgi8e16sit` (`time_id` ASC),
  CONSTRAINT `FKk4nxa3jk494rjdtmgi8e16sit`
    FOREIGN KEY (`time_id`)
    REFERENCES `hospital`.`time_quantum` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK6dwehthu61quieqm0dhcf45dt`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospital`.`patient` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKdn9ekl8482cpt21remcdi8cy9`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `hospital`.`doctor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
